spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - data-prod
  resources:
    static-locations: classpath:/static/reports

security:
  jwt:
    token:
      validtime:
        access: 21600000
        refresh: 2073600000
        clientSecret: 3600000
      secretkey: {TOKEN_SECRETKEY}