spring:
  config:
    use-legacy-processing: true
  profiles:
    include:
      - data
  resources:
    static-locations: classpath:/static/reports

security:
  jwt:
    token:
      validtime:
        access: 31557600000
        refresh: 31557600000
        clientSecret: 3600000
      secretkey: jwtsecretKeyhastolonghowlongidontknow